= Char! datatype
Version: First Draft
:toc:
:numbered:

== Abstract

`Char!` values represent a Unicode code point. It is an integer number in the range hexadecimal 00 to hexadecimal 10FFFFF. (0 to 1,114,111 in decimal.) 

== Characteristics
'Char!' values are 'direct', 'atomic' and 'passive'.

Note: This assumes that Type Characteristics have been defined earlier in the document.

== Creation

`Char!` values can be created using literal syntax or at runtime by using a 'make' constructor, a `to` conversion or using one of the many functions that act on `string!` values to extract a `char!` value.

=== Literal syntax

There are three literal formats for char! values.
----
#"<character>"
<character> : a single displayable character representing the code point

#"^<escaped-character>"
<escaped-character> : one of /-~^"
    #"/"                ;-- newline
	  #"-"                ;-- tab  
	  #"~"                ;-- del
	  #"^""               ;-- double quote
		
#"^(<hexadecimal>)"
<hexadecimal> : a single code point number in hexadecimal 
----

== Comparisons

All comparators can be applied on 'char!' values: `=, ==, <>, >, <, >=, &lt;=, same?`. In addition, `min`, `max` and `sort` are supported. Comparison of `char!` values is case sensitive.

*Examples*
----
#"a" = #"A"
== false
same? #"a" #"a"
== true
max #"a" #"A"
== #"a"
sort [#"c" #"b" #"d" #"a"]
== [#"a" #"b" #"c" #"d"]
----

== Arithmetic
The full range of mathematical functions can be used with `char!` values. A `Math Error` is raised if the result of the arithmetic falls outside of the range 00 - 10FFFF (hexadecimal).

*Examples*
----
#"a" + 1
== #"b"
#"a" - 32
== #"A"
#"a" * 256
== #"愀"
#"a" - 98
*** Math Error: math or number overflow
*** Where: -
*** Stack:  

----
== Other char-related functions

Lowercase, Uppercase

