= Date! datatype
:toc:
:numbered:

== Abstract

`date!` values represent commonly used dates, relying on the Gregorian calendar. A date value can optionally also contain a time and a timezone information. Time in dates is expressed in 24-hour format (including optional time zone information). Red's dates also have an extensive support for https://en.wikipedia.org/wiki/ISO_8601[ISO 8601] input formats.

Note:

* `date!` uses a https://en.wikipedia.org/wiki/Proleptic_Gregorian_calendar[proleptic Gregorian calendar], extending its usage backward, beyond the year 1582. So care should be taken when trying to represent historical pre-Gregorian dates using `date!` values.

* Supported dates range from `1/Jan/-32768` to `31/Dec/32767`, wrapping around on overflowing math operations. On input, that range is reduced to `1/Jan/-9999` to `31/Dec/9999` for practical reasons.

== Creation

`Date!` values can be created using a literal syntax, or at runtime using `make` constructor or a `to` conversion.

=== Literal syntax
----
<date>/<time>
<date>/<time><zone>
<date>T<time>
<date>T<time>Z
<date>T<time><zone>

<date> formats:
    <yyyy><sep><m><sep><dd>
    <dd><sep><m><sep><yyyy>
    <dd><sep><m><sep><yy>

<m> formats (month):
    <mm>
    <mon>
    <month>

<time> formats:
    <hour>:<min>:<sec>
    <hour>:<min>:<sec><zone>

<zone> formats (timezone):
    <sign><hour>
    <sign><hour>:<min15>
    <sign><hhmm>
    
<sec> formats (seconds):
    <ss>
    <ss>.<dec>

<yyyy>  : 4 digits representing the year
<yy>    : 2 digits representing the year relative to 2000
<mm>    : 1 or 2 digits representing the month
<mon>	: 3 letters representing the beginning of the month
<month> : full name of the month
<dd>    : 1 or 2 digits representing the day of the month
<time>  : time! value
<hour>  : 1 or 2 digits representing the hours
<min>   : 1 or 2 digits representing the minutes
<ss>    : 1 or 2 digits representing the seconds
<dec>   : decimals for seconds
<sign>  : `+` or `-` character (cannot be omitted)
<min15> : same as <min> but rounded to 15 minutes steps.
<hhmm>  : 4 digits representing hour and minutes (no separator)
----

Many different input formats for literal dates are accepted. Out of range values (exceeding the specified digit numbers or beyond a field's norm) will result in a syntax error. When serialized again (e.g. for displaying), only the following canonical display formats are used:

----
<dd>-<mon>-<yyyy>/<hour>:<min>:<sec><sign><hour>:<min15>
<dd>-<mon>-<yyyy>
----
When the time and zone fields are unset or set to zero, they are both omitted. For negative dates, the `/` separator is used instead of `-` for better readability.

Notes:

* When a month is specified using letters, the month is expressed using its English name, and is case-insensitive.
* When a year is specified using the 2 digits format `yy`, if it is < 50, it's interpreted as `20yy`, otherwise, it's interpreted as `19yy`.

Examples of valid input dates:
----
1999-10-5
1999/10/5
5-10-1999
5/10/1999
5-October-1999
1999-9-11
11-9-1999
5/sep/2012
5-SEPTEMBER-2012

02/03/04
02/03/71

5/9/2012/6:0
5/9/2012/6:00
5/9/2012/6:00+8
5/9/2012/6:0+0430
4/Apr/2000/6:00+8:00
1999-10-2/2:00-4:30
1/1/1990/12:20:25-6

2017-07-07T08:22:23+00:00
2017-07-07T08:22:23Z
20170707T082223Z
----


=== Runtime creation
----
make date! [<day> <month> <year>]
make date! [<year> <month> <day>]
make date! [<day> <month> <year> <time>]
make date! [<day> <month> <year> <time> <zone>]
make date! [<day> <month> <year> <hour> <minute> <second>]
make date! [<day> <month> <year> <hour> <minute> <second> <zone>]

<year>   : integer! value
<month>  : integer! value
<day>    : integer! value
<time>   : time! value
<zone>   : integer!, time! or pair! value
<hour>   : integer! value
<minute> : integer! value
<second> : integer! value
----

Notes:

* Out of range argument values will result in an error. For a normalized result, use the `to` action instead of `make`.

* `year` and `day` fields are interchangeable, but for low years value, the year can be used in first position only if its value >= 100 and less than the value of the third field. When that rule is not satisfied, the third field is considered the year. Negative years should always be specified in last position.

Examples:
----
make date! [1978 2 3]
== 3-Feb-1978

make date! [1978 2 3 5:0:0 8]
== 3-Feb-1978/5:00:00+08:00

make date! [1978 2 3 5:0:0]
== 3-Feb-1978/5:00:00

make date! [1978 2 3 5 20 30]
== 3-Feb-1978/5:20:30

make date! [1978 2 3 5 20 30 -4]
== 3-Feb-1978/5:20:30-4:00
----

== Path accessors

Path accessors provide a convenient way for getting and setting access to all the `date!` value fields.

=== /year

*Syntax*
----
<date>/year
<date>/year: <year>

<date> : a word or path expression referring to a date! value
<year> : an integer! value
----
*Description*

Gets or sets the year field of a date. Years are returned as integers. Out of range argument values will result in a normalized date.

=== /month

*Syntax*
----
<date>/month
<date>/month: <month>

<date>  : a word or path expression referring to a date! value
<month> : an integer! value
----
*Description*

Gets or sets the month field of a date. Months are returned as integers. Out of range argument values will result in a normalized date.

=== /day

*Syntax*
----
<date>/day
<date>/day: <day>

<date> : a word or path expression referring to a date! value
<day>  : an integer! value
----
*Description*

Gets or sets the day field of a date. Days are returned as integers. Out of range argument values will result in a normalized date.

=== /time

*Syntax*
----
<date>/time
<date>/time: <time>

<date> : a word or path expression referring to a date! value
<time> : a time! value
----
*Description*

Gets or sets the time field of a date. Times are returned as `time!` values. Out of range argument values will result in a normalized date.

=== /hour

*Syntax*
----
<date>/hour
<date>/hour: <hour>

<date> : a word or path expression referring to a date! value
<hour> : an integer! value
----
*Description*

Gets or sets the time field of a date. Hours are returned as integer values between 0 and 23. Out of range argument values will result in a normalized date.

=== /minute

*Syntax*
----
<date>/minute
<date>/minute: <minute>

<date>   : a word or path expression referring to a date! value
<minute> : an integer! value
----
*Description*

Gets or sets the minute field of a date. Minutes are returned as integer values between 0 and 59. Out of range argument values will result in a normalized date.

=== /second

*Syntax*
----
<date>/second
<date>/second: <second>

<date>   : a word or path expression referring to a date! value
<second> : an integer! or float! value
----
*Description*

Gets or sets the second field of a date. Seconds are returned as `integer!` or `float!` values between 0 and 59. Out of range argument values will result in a normalized date.

=== /zone

*Syntax*
----
<date>/zone
<date>/zone: <zone>

<date> : a word or path expression referring to a date! value
<zone> : an integer!, time! or pair! value
----
*Description*

Gets or sets the timezone field of a date. Timezones are returned as `time!` values between -16:00 and +15:00. Setting the timezone with `/zone` will only modify that field, time is kept the same. Out of range argument values will result in a normalized date.

When the timezone is set to an `integer!` argument, the argument represents hours and minutes are set to 0. When the timezone is set to a `pair!` argument, the left pair part is the hours and the right part, the minutes.

The granularity for timezone's minutes is 15, non-conforming values will be truncated to closest 15 minutes values.

*Examples*
----
d: 1/3/2017/5:30:0
d/zone: 8
== 1-Mar-2017/5:30:00+08:00

d/zone: -4:00
== 1-Mar-2017/5:30:00-04:00

d/zone: 12x15
== 1-Mar-2017/5:30:00+12:15
----

=== /timezone

*Syntax*
----
<date>/timezone
<date>/timezone: <zone>

<date>     : a word or path expression referring to a date! value
<timezone> : an integer!, time! or pair! value
----
*Description*

Gets or sets the timezone field of a date. Timezones are returned as `time!` values between -16:00 and +15:00. Setting the timezone with `/timezone` will modify both the time and the timezone, keeping the new time equivalent to the old one in the new timezone. Out of range argument values will result in a normalized date.

When the timezone is set to an `integer!` argument, the argument represents hours and minutes are set to 0. When the timezone is set to a `pair!` argument, the left pair part is the hours and the right part, the minutes.

The granularity for timezone's minutes is 15, non-conforming values will be truncated to closest 15 minutes values.

*Examples*
----
d: 1/3/2017/5:30:0
d/timezone: 8
== 1-Mar-2017/13:30:00+08:00

d/timezone: -4:00
== 1-Mar-2017/1:30:00-04:00

d/timezone: 12x15
== 1-Mar-2017/17:45:00+12:15
----

Note:

* Setting the `/timezone` to 0 will set the time to UTC.

=== /yearday

*Syntax*
----
<date>/yearday
<date>/yearday: <day>

<date>    : a word or path expression referring to a date! value
<yearday> : an integer! value
----
*Description*

Gets the day of the year of a date, starting at 1 for January 1st. Days are returned as integers. When used for setting the day of the year, the date is recalculated to match that day. Out of range argument values will result in a normalized date.

Note:

* a `/julian` alias for `/yearday` is also available, for compatibility with Rebol.

=== /weekday

*Syntax*
----
<date>/weekday
<date>/weekday: <day>

<date>    : a word or path expression referring to a date! value
<weekday> : an integer! value
----
*Description*

Gets the week day number, ranging from 1 for Monday, to 7 for Sunday. When used for setting the day of the week, the date is recalculated to match that day in the current week. Out of range argument values will result in a normalized date.

=== /week

*Syntax*
----
<date>/week
<date>/week: <day>

<date> : a word or path expression referring to a date! value
<week> : an integer! value
----
*Description*

Gets the week number using a casual week definition (week starts on Sunday, first week starts on January 1st), ranging from 1 for first week of the year, to 53. When used for setting the week number, the date is recalculated to match the first day of that week (a Sunday). Out of range argument values will result in a normalized date.

Note:

* The casual week definition allows first and last weeks of the year to be partial weeks, ranging from 1 day to 7 days. For accurate week calculations across years, use the `/isoweek` accessor.

=== /isoweek

*Syntax*
----
<date>/isoweek
<date>/isoweek: <day>

<date>    : a word or path expression referring to a date! value
<isoweek> : an integer! value
----
*Description*

Gets the week number using the https://en.wikipedia.org/wiki/ISO_week_date[ISO 8601] week definition, ranging from 1 for first week of the year, to 52 (or 53 for some years). When used for setting the week number, the date is recalculated to match the first day of that week (a Monday). Out of range argument values will result in a normalized date.

=== Ordinal accessors

In addition to using words for accessing the date fields, it is also possible to use an integer index in path expression:

----
<date>/<index>

<date>  : a word or path expression referring to a date! value
<index> : an integer! value referring to a date field.
----

Such ordinal accessor can be used both for getting or setting fields. The following table gives the equivalent field names

[cols="1,1",options="header",align="center"]
|===
|Index | Name
| 1| year
| 2| month
| 3| day
| 4| zone
| 5| time
| 6| hour
| 7| minute
| 8| second
| 9| weekday
|10| yearday
|11| timezone
|12| week
|13| isoweek
|===

=== Accessing date fields using Pick

It is possible to access date fields without using a path, which can be more convenient in some cases. `pick` can be used for that on dates.

*Syntax*
----
pick <date> <field>

<date>  : a date! value
<field> : an integer! value
----

An integer argument represent the ordinal accessor for dates. See "Ordinal accessors" table above.

== Conversions

=== Epoch time

Dates can be converted from/to https://en.wikipedia.org/wiki/Unix_time[Unix epoch time] using `to` action.

*Syntax*
----
to integer! <date>
to date! <epoch>

<date>  : a date! value
<epoch> : an integer value representing an epoch time
----

Epoch time are expressed in UTC, so timezones should be set to zero (if not the case already), before converting a date to an epoch time. This can be achieved easily using the `/timezone` accessor:
----
d: 8-Jul-2017/17:49:27+08:00
d/timezone: 0
== 8-Jul-2017/9:49:27

to integer! 8-Jul-2017/9:49:27
== 1499507367

to date! to integer! d
== 8-Jul-2017/9:49:27
----

=== Block to date

*Syntax*
----
to date! <spec>

<spec> : a block of values for date fields
----
The argument block will be converted to a `date!` value according to the same syntax as for `make` (see 2.2 Runtime creation). Out of range argument values will result in a normalized date. For a restrictive conversion from block, use `make`.

== Comparisons

All comparators can be applied on dates: `=, ==, <>, >, <, >=, &lt;=, same?`. In addition to that, `min`, `max` and `sort` are also supported.

*Examples*
----
3-Jul-2017/9:41:40+2:00 = 3-Jul-2017/5:41:40-2:00
== true

10/10/2017 < 1/1/2017
== false

max 10/10/2017 1/1/2017
== 10-Oct-2017

same? 1/1/1980 1-JAN-1980
== true

sort [1/1/2017 5/10/1999 3-Jul-2017/5:41:40-2:00 1/1/1950 1/1/1980/2:2:2]
== [1-Jan-1950 1-Jan-1980/2:02:02 5-Oct-1999 1-Jan-2017 3-Jul-2017/5:41:40-02:00]
----

== Arithmetic

Supported math operations on dates include:

* adding or subtracting values from any date field (result is normalized).
* adding or subtracting an integer value to date value (interpreted as a number of days).
* subtracting two date values: result in a signed number of days between those two dates.
* using the `difference` function on two date values: result is the signed time difference between those two dates.

*Examples*
----
20-Feb-1980 + 50
== 10-Apr-1980

20-Feb-1980 + 3
== 23-Feb-1980

20-Feb-1980 - 25
== 26-Jan-1980

20-Feb-1980 + 100
== 30-May-1980

d: 20-Feb-1980
d/day: d/day + 50
== 10-Apr-1980

d: 20-Feb-1980
d/month: d/month + 5
== 20-Jul-1980

d: 28-Feb-1980/8:30:00
d/hour: d/hour + 48
== 1-Mar-1980/8:30:00

08/07/2017/10:45:00 - 20-Feb-1980/05:30:0
== 13653

difference 08/07/2017/10:45:00 20-Feb-1980/05:30:0
327677:15:00
----

== Getting current date

The `now` function returns the operating system's current date and time (including timezone). All the date path accessors are available to `now` as refinements. There is an additional `/utc` refinement to get the date in UTC format.

*Examples*
----
now
== 8-Jul-2017/18:32:25+08:00

now/year
== 2017

now/hour
== 18

now/month
== 7

now/day
== 8

now/hour
== 18

now/zone
== 8:00:00

now/utc
== 8-Jul-2017/10:32:25
----

== Other date-related functions

=== Random