= Glossary
Version: Draft 1

[glossary]
Action:: 
  One of a fixed set of functions all datatypes may support. Not all datatypes support all actions.
Actor::
  
all-word!::
  
any-block!::
  
any-function!::
  
any-list!::
  
any-object!::
  
any-path!::
  
any-string!::
  
any-type!::
  
any-word!::
  
Block::
    
Compiler::
    
Console::
    
Datatype::
  Datatypes are the foundation of Red...
default!::
  
Draw::
    
Event::
    
external!::
  
Face::
    
Facet::
    
immediate!::
 
Op::
  A function with an infix interface, where the first arg appears to the left of the function name. 
internal!::
  
Interpreter::
    
Layout::
    
libRed::
    
List::
  
Mezzanine::
  Another name for a Red function.
Native:: 
  Functions written in Red/System, and exposed for use in Red.  
Number::
    
number!::
    
Pane::
    
Path::
  
Pseudo-type::
  An informal name for `typeset`.
Routine::
  A Red/System function written inline in Red.  
Runtime::
    
scalar!::
    
Series::
    
series!::
  
String::
    
Typeset::   
  Typesets are groupings of datatypes with shared characteristics...
Toolchain::
    
VID::
    
View::
    
Word::
    