= Integer! datatype
:toc:
:numbered:

== Abstract

Integer values are 32-bit positive and negative numbers with no decimal point.

Integer spans a range from `-2147483648` to `2147483647`.

By design `integer!` does not auto convert to `float!` on overflow.


== Literal syntax

A sequence of digits with no decimal point.

`1234`

`+` or `-` immediately before the first digit indicates the positive or negative sign of the integer.

`-1234`

`+1234`

Leading zeros are ignored.
----
>> +001234
== 1234
----

Single quote `'` is used as a place value seperator for long integers and can appear anywhere after the first digit.

----
60'000'000
----


== Comparisons

All comparators can be applied on integers: `=, ==, <>, >, <, >=, &lt;=, =?`. In addition, `min`, and `max` are also supported.


== Conversion

An integer value can be converted at runtime to `float!` or `string!` by using the `to` action.

----
>> to float! 42
== 42.0

>> to string! 42
== "42"
----

If `integer!` and `float!` are combined in an expression, the result will be `float!`.

----
>> 42 * 42.0
== 1764.0
----


== Testing values

Use `integer?` to check if a value is an `integer!` datatype.

----
>> integer? 42
== true
----

Use `type?` to return the datatype of a given value.

----
>> type? 42
== integer!
----

