= Red Programming Language Documentation

== English version

_This is a work in progress, only a few pieces are available as reference documentation._

For more information about Red language, please visit http://red-lang.org


Join the chat at  https://gitter.im/red/docs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge[image:https://badges.gitter.im/red/docs.svg[https://gitter.im/red/docs]]

== Howto for documentation translators

* Navigate to https://github.com/red/docs[red/docs]. Click the `Fork` button.
* Check your github profile to ensure that the fork was successful.
* Using git command line, clone your fork to bring the `docs` files to your local machine.
** `git clone https://github.com/<your-github-profile>/docs.git`

* In your favorite editor, open the docs directory that has been cloned to your local machine and create a new language folder. 
Name it with the language code for the language you are translating. https://iso639-3.sil.org/code_tables/639/data/all[Language Codes]

* Copy the document that you wish to translate from the `en` folder  to the new language folder and make your edits in the copied file.

*Example git workflow*

* Make sure your Fork is up to date with `red/docs`.

** `git pull https://github.com/red/docs.git`

* After translating each file, add the file to your git index.

** `git add <your-translated-file>`

* Commit the file with a message.

** `git commit -m "Your message."`

* When you are finished translating files, push your files to your Fork.

** `git push https://github.com/<your-github-profile>/docs.git`

* Once your files have been pushed to your Fork, click the `New pull request` button on GitHub to create a Pull Request.

