= Le type Tag!
:toc:
:numbered:

== Résumé

Les valeurs du type `Tag!` représentent des tags et éléments d'un langage de balisage (markup language).

`Tag!` appartient aux ensembles de types suivants: `any-string!`, `series!`

== Création

Les valeurs de type Tag! peuvent être créées à l'aide de la syntaxe littérale, ou à l'exécution en utilisant le constructeur `make` ou la conversion `to`.

```red
>> make tag! "foo"
== <foo>
```

```red
>> to tag! 'bar
== <bar>
```

== Syntaxe littérale

Un ou plusieurs caractères placés entre le signe `<` et le signe `>`.

Le premier caractère qui suit le signe ouvrant `<` ne peut être `<`, `>`, ou `=`. 

Aucun caractère d'espace n'est autorisé entre le signe ouvrant `<` et le premier caractère, car l'interpréteur analyserait celui-ci comme un opérateur de comparaison invalide.

```red
>> < foo>
*** Script Error: < operator is missing an argument
*** Where: catch
*** Stack:  
```

== Comparaisons

Tous les comparateurs peuvent être appliqués à `Tag!`: `=, ==, <>, >, <, >=, &lt;=, =?`. De plus, `min`, et `max` sont aussi supportés.

== Test de valeurs

Utilisez `tag?` pour vérifier si une valeur est du type `Tag!`.

```red
>> tag? <foo>
== true
```

Utilisez `type?` pour connaître le type d'une valeur donnée.

```red
>> type? <foo>
== tag!
```

== Mots prédéfinis

=== Fonctions

`tag?`, `to-tag`