= Le type Typeset!
:toc:
:numbered:

== Résumé

A `typeset!` value represents a set, or collection, of predefined `datatype!` values.

`Typeset!` appartient aux ensembles de types suivants: `default!`, `immediate!`

== Création

Les valeurs de type `Typeset!` peuvent être créées by using le constructeur `make` ou la conversion avec `to`.

== Syntaxe littérale

By convention, literal syntax is a `word!` value ending with an exclamation mark `!`.

Examples: `any-list!`, `number!`, `series!`

=== Runtime creation

```
<typeset> ::= make typeset! [<typeset-element>*]
<typeset-element> ::= <typeset-name> | <datatype-name>
```

*Examples*

```red
>> number!: make typeset! [integer! float! percent!]
== make typeset! [integer! float! percent!]

>> collection!: make typeset! [block! paren! map!]
== make typeset! [block! paren! map!]

>> to typeset! [integer! float! percent!]
== make typeset! [integer! float! percent!]
```

Empty typesets are allowed.

```red
>> empty!: make typeset! []
== make typeset! []
```

== Conversions

A `typeset!` value can be converted to any value of the typeset `any-list!`

```red
>> to block! number!
== [integer! float! percent!]

>> to paren! number!
== (integer! float! percent!)

>> to hash! number!
== make hash! [integer! float! percent!]
```

== Comparaisons

No comparisons are supported for `typeset!`.

== Data set operations

The following data set operations are possible with `typeset!` values: 

`difference`, `exclude`, `intersect`, `union`

== Test de valeurs

Utilisez `typeset?` pour vérifier si une valeur est du type `Typeset!`.

```red
>> typeset? number!
== true
```

Utilisez `type?` pour connaître le type d'une valeur donnée.

```red
>> type? number!
== typeset!
```

== Predefined words

=== Actions

`and~`, `complement`, `find`, `or~`, `xor~`

=== Fonctions

`to-typeset`

=== Natives

`difference`, `exclude`, `intersect`, `union`

=== Opérateurs

`and`, `or`, `xor`