= How-to for documentation translators

* Navigate to https://github.com/red/docs[red/docs]. Click the `Fork` button.
* Check your github profile to ensure that the fork was successful.
* Using git command line, clone your fork to bring the `docs` files to your local machine.
** `git clone https://github.com/<your-github-profile>/docs.git`

* In your favorite editor, open the docs directory that has been cloned to your local machine and create a new language directory.  
Name the new directory using the appropriate language code for the language that you are translating. https://iso639-3.sil.org/code_tables/639/data/all[Language Codes]

* Copt the `styles` directory into the newly created language directory.

* Copy the document that you wish to translate from the `en` directory to the newly created language directory. Make your edits to the copied document. 

*Example git workflow*

* Make sure your Fork is up to date with `red/docs`.

** `git pull https://github.com/red/docs.git`

* After translating each file, add the file to your git index.

** `git add <your-translated-file>`

* Commit the file with a message.

** `git commit -m "Your message."`

* When you are finished translating files, add a language link to `LANGS.adoc` then push your files to your Fork.

** `git add LANGS.adoc`

** `git commit -m "Added link for <language-code>"`

** `git push https://github.com/<your-github-profile>/docs.git`

* Once your files have been pushed to your Fork, click the `New pull request` button on GitHub to create a Pull Request.

