= Char! datatype
Version: Draft 3
:toc:
:numbered:

== Úvodem

Hodnoty typu `char!` odkazují na kódové body (code points) znakové sady  Unicode, jimiž jsou celá čísla v rozsahu od hexadecimální nuly (00) do hexadecimální hodnoty 10FFFF.

Znaky (characters) mohou být tisknutelné (viewable) nebo řídící netisknutelné (escaped or control). Řídící znak je kódový bod v sadě znaků, který nereprezentuje psaný symbol. 

V Redu jsou řídící znaky předznamenány symbolem `^` (caret).

Typ `char!` je členem typesetů `immediate!`, `scalar!` a `default!`.

== Vytvoření

Hodnoty `char!` mohou být vytvořeny s použitím literálové syntaxe nebo při běhu programu s použitím konstruktoru 'make' či konverzí  'to'  nebo jednou z mnoha funkcí, které z hodnoty `string!` extrahují hodnotu `char!`.


=== Literálová syntaxe

Formát hodnoty typu `char!` je tento:
----
<char-lit>     :: = #"<single-char>"

<single-char>  :: = <viewable-char> | <escaped-char> | <hex-codepoint>
<vieable-char> :: = zobrazený znak, zadaný z klávesnice
<escaped-char> :: = ^(null) or ^@ | ^(back) or ^H | ^(tab) or ^_
                    ^(line) or ^/ | ^(page) or ^L | ^(esc) or ^[
                    ^(del)  or ^~ | ^A|^B| ... ^Z |
                    ^] | ^" | ^^
<hex-codepoint>:: = ^(hex-number)
hex-number     :: = platné hexadecimální číslo 00 až 10FFFF					
----

Únikovým znakem (escape character) v Redu je `^` (U+005E). V důsledku toho musí být samotný znak `^` rovněž předsazen únikovým znakem. Stringový literál pro tento znak je #"^^", nikoliv #"^"; označení #"^" je neplatné.

V Redu existují tři formy únikových literálů, jeden pro číselné kódové body, další pro pojmenované znaky a poslední pro "řídící" znaky.

Formát grafického znaku je:
----
#"^(<codepoint>)"
<codepoint> : platné hexadecimální číslo 00 až 10FFFF
----

Formát řídícího znaku je:
----
#"^<cc>"
----
kde <cc> je jeden znak sady &nbsp; `A-Z`, `[`(escape), `\`(line feed), `]`(group separator, `_` (unit separator), například:
```red


.Únikové řídící znaky
[cols="3*"]
|===

|Únikový znak
|Codepoint
|Jméno

|#"^A" - #"^Z"
|U+0001 - U+001A
|

|#"^["
|U+001B
|escape

|#"^\"
|U+001C
|line feed

|#"^]"
|U+001D
|group separator

|#"^_"
|U+001F
|unit separator
|===

Formát "pojmenovaných" znaků je:
----
#"^(<name>)" nebo #"^<symbol>" 
<name> : název z tabulky Únikové řídící znaky
<symbol> : symbol z tabulky Únikové řídící znaky
----

.Pojmenované únikové znaky
[cols="4*"]
|===

|name
|symbol
|character
|codepoint

|#"^(null)"    
|#"^@"    
|null                
|U+0000

|#"^(back)"   
|#"^H"
|backspace           
|U+0008

|#"^(tab)"    
|#"^I" #"^-" 
|horizontal tab      
|U+0009

|#"^(line)"    
|#"^J" #"^/"   
|new line           
|U+000A 

|#"^(page)"   
|#"^L"
|new page           
|U+000C

|#"^(esc)"    
|#"^["
|escape              
|U+001B

|#"^(del)"    
|#"^~"   
|delete              
|U+007F

|
|#"^""                      
|double quote 
|U+0022

|
|#"^^"
|caret char.           
|U+005E

|
|#"^A" - #"^]"
|control chars           
|U+0001-U+001D

|
|#"^_"
|control char.           
|U+001F
|===


== Komparace

Pro hodnoty typu 'char!' mohou být použity všechny komparátory : `=, ==, <>, >, <, >=, &lt;=, =?`. Navíc jsou podporovány `min`, `max` a `sort`. Porovnávání hodnot typu `char!` values je 'case sensitive'.

*Příklady*

----
#"a" = #"A"
== false
#"a" =? #"a"
== true
max #"a" #"A"
== #"a"
sort [#"c" #"b" #"d" #"a"]
== [#"a" #"b" #"c" #"d"]
----


== Aritmetika
Pro hodnoty `char!` lze použít celý rozsah matematických funkcí. Pokud se výsledek aritmetického výrazu dostane mimo rozsah  00 - 10FFFF (hexadecimal), je vyvolána chyba `Math Error`.

*Příklady*

----
#"a" + 1
== #"b"
#"a" - 32
== #"A"
#"a" * 256
== #"愀"
#"a" - 98
*** Math Error: math or number overflow
*** Where: -
*** Stack:  

----



== Další souvisící funkce

Lowercase, Uppercase

