= Datový typ `email!`
:toc:
:numbered:

== Úvodem

Hodnoty typu `email!` umožňují přímé vyjádření emailových adres, např. `foo@bar.net`

`Email!` je člen typesetů `any-string!` a `series!`

== Vytvoření

Hodnoty typu `email!` lze vytvořit s použitím literálové syntaxe nebo při runtime použitím konstruktoru `make` či konverzí `to`.

== Literálová skladba

Jeden nebo více znaků, následovaných symbolem `@`, doplněným dalšími znaky.

*Příklady*

```
foo@bar.net
gregg@red-lang.org
g@
```

*Neplatné znaky* 

`%` `(` `)` `:` `"`

== Vytvoření při runtime

=== make


```red
>> f: make email! "foo"
== foo

>> type? f
== email!
```
=== to


```red
>> b: to email! 'bar
== bar

>> type? b
== email!
```

== Path accessors

Přístupy formou cesty poskytují vhodný způsob získání či zadání jména uživatele nebo hostitele v emailové adrese.

=== /user

```red
>> e: me@me.net
== me@me.net

>> e/user
== "me"

>> e/user: "you"
== "you"

>> e
== you@me.net
```

=== /host

```red
>> e/host
== "me.net"

>> e/host: "red-lang.org"
== "red-lang.org"

>> e
== you@red-lang.org
```

== Komparace

Lze použít všechny komparátory: `=, ==, <>, >, <, >=, &lt;=, =?`. Navíc jsou podporováy také funkce `min` a  `max`.

== Testování hodnot

K ověření typu hodnoty slouží funkce `email?`.

```red
>> email? foo@bar.net
== true
```

Datový typ dané hodnoty vrací funkce `type?`.

```red
>> type? foo@bar.net
== email!
```

== Předdefinovaná slova

=== Funkce

`email?`, `suffix?`, `to-email`