= Datový typ paren!
:toc:
:numbered:

== Úvodem

Datový typ `paren!` je řada elementů libovolného typu, obklopená kulatými závorkami `(` a `)`. Obsah uvnitř závorek není, na rozdíl od obsahu běžných závorek, okamžitě vyhodnocován.

Objekt paren lze vytvořit literálovou syntaxí nebo při runtime použitím konstruktoru `make`, konverzí `to` nebo funkcí `as`.

== Literálová skladba

Vyhodnocení obsahu mezi závorkami lze potlačit slovem `quote` před závorkou, což je nutné provést při deklaraci objektu nebo při introspekci `length?`, `type?`, `paren?`.

```red
>> pr: quote (2 + 3)
== (2 + 3)

>> par: quote (one 2 "three")
== (one 2 "three")

>> length? quote (one 2 "one")
== 3

>> length? (1 2 "one")
== 5
```
Bez příkazu `quote` tvoří závorka (paren) jakýsi `semi-paren`:

```red
>> type? (1 2 "one")
== string!

`Paren!` je členem typesetů: `any-list!`, `any-block!`, `series!`.

Pareny lze rozepsat do více řádů a mohou obsahovat další pareny.

```red
quote (1
2
"three"
)

pp: quote (1 2 "three" (x foo 1.23))
== (1 2 "three" (x foo 1.23))
```

Řádky, mezery a tabulátory jsou dovoleny, pokud nerozdělují hodnoty.

Ok:  `(print "foo")`

Not ok: `(pr   int "foo")`

== Konstruktorová skladba

Prázdný paren pro 10 elementů vytvoříme příkazem:

```red
>> make paren! 10
== ()
```

Paren s deseti elementy počáteční hodnoty `none`:

```red
>> append/dup make paren! 10 none 10
== (none none none none none none none none none none)
```

Použití konverze `to`:

```red
>> to paren! {one 2 "three" 4:00}
== (one 2 "three" 4:00:00)

>> to paren! "foo 1.23 me@me.com"
== (foo 1.23 me@me.com)

>> to paren! 42
== (42)
```

Použití `as`:

```red
>> as paren! [1 2 3]
== (1 2 3)
```

Objekt typu paren! můžeme vytvořit odkazem na počátek bloku: 

```red
>> par: first [(1 + 2 * 3 / 4)]
== (1 + 2 * 3 / 4)
>> do par
== 2 

== Komparace

Lze použít všechny komparátory `=, ==, <>, >, <, >=, &lt;=, =?`, včetně funkcí `min` a `max`.

[NOTE]
Protože jsou hodnoty objektu typu `paren!` ihned vyhodnocovány, je vratnou hodnotou funkcí `min` nebo `max` hodnota posledního výrazu v parenu. Komparátory porovnávají poslední elementy porovnávaných parenů, není-li jejich vyhodnocení potlačeno.

```red
>> max (1 2 3) (4 5 6)    ; TO NENÍ PAREN!
== 6

>> p1: quote (1 2 3)
== (1 2 3)
>> p2: quote (4 5 6)
== (4 5 6)

>> max p1 p2
== (4 5 6)
```


```red
>> (1 2 3) < (4 5 6)
== true

>> (1 2 3) < (4 5 2)
== false

>> (quote (1 2 3)) < (quote (4 5 2))
== true
```


== Testování hodnot

Použijte funkci `paren?` k ověření, zda je posuzovaná hodnota typu  `paren!`.

```red
>> paren? quote (42 print "foo")
== true

ALE !:

>> paren? (42 print "foo")    
foo
== false                         ; proč?

>> type? (42 print "foo")        ; protože
foo
== unset!

>> type? quote (42 print "foo")
== paren!                     
```

[NOTE, caption=Poznámka]

Neparafrázované (unquoted) hodnoty paren vrací typ poslední hodnoty

```red
>> paren? (42)
== false

>> any-list? (42)
== false

>> type? (42)
== integer!

>> type? ('a 2 + 2 "hello")
== string!

>> type? (42 print "foo")
foo
== unset!
```

[NOTE]
Není to tak, že máme neparafrázovaný paren

```red
>> prn: (2 + 3)
== 5
```
a parafrázovaný paren?

```red
>> prp: quote (2 + 3)
== (2 + 3)
```
Je-li to pravda, nutno upravit předchozí text.


== Předdefinovaná slova

=== Funkce

`expand-directives`, `paren?`, `series?`, `to-paren`

=== Natives

`as`, `compose`
