= Datový typ `refinement!`
:toc:
:numbered:


== Úvodem

Hodntoty typu `refinement!` (upřesnění) jsou symbolické hodnoty, používané jako modifikátory *funkcí* nebo jako extenze u *objektů*, *souborů*, *URL* nebo *cest*. 


Funkce `repend` bez upřesnění:
```red
>> repend ["foo"] [21 * 2]
== ["foo" 42]
```

S upřesněním `/only`:

```red
>> repend/only ["foo"] [21 * 2]
== ["foo" [42]]
```

Datový typ `refinement!` je subtypem typesetů `all-word!` a `immediate!`.


== Vytvoření

Hodnoty typu refinement! lze vytvořit použitím `literálové skladby` při načítání skriptu nebo při runtime konstruktorem `make` či konverzí `to`.

```red
>> /foo
== /foo
```
 
```red
>> make refinement! "bar"
== /bar
```
```red
>> to refinement! 'baz
== /baz
```


== Literálová skladba

Lomíko `/`, následované jedním či více znaky sady Unicode, včetně interpunkčních znaků ze sady ASCII:  `! & ' * + - . < = > ? _ | ~``

Nepovolenými znaky jsou řídící znaky, znaky mezer a interpunkční znaky ze sady ASCII: `/ \ ^ , [ ] ( ) { } " # $ % @ : ;`

[NOTE, caption=Note]

Použití znaku `@` nevyvolá chybu, ale způsobí, že se hodnota `refinement!` vrátí jako `email!`.



== Komparace

Na `refinement!` lze aplikovat všechny komparátory: `=, ==, <>, >, <, >=, &lt;=, =?`. 

== Testování hodnot

Funkce `refinement?` slouží k ověření, zda je zadaná hodnota typu `refinement!`.

```red
>> refinement? /foo
== true

>> refinement? third [42 "Foo" /bar]
== true
```

Funkce `type?` vrací datový typ zadané hodnoty.

```red
>> type? /foo
== refinement!

>> type? third [42 "Foo" /bar]
== refinement!
```

== Předdefinovaná slova

=== Funkce

`parse-func-spec`, `refinement?`, `to-refinement`

=== Natives

`function`
