= Float! datatype
:toc:
:numbered:


== Abstract

`Float!` values are 64-bit positive and negative numbers that contain a decimal point.

Floats span a range from `-1.7E+308` to `+1.7E+308`.

Floats returns #INF on overflow by design.

----
>> 1.8E+308
== 1.#INF

>> -1.8E+308
== -1.#INF
----

Dividing `0.0` by `0.0` results in `1.#NaN`


== Literal syntax

A sequence of digits with a decimal point or comma.

`123.4`

`123,4`

`+` or `-` immediately before the first digit indicates the positive or negative sign of the `float!`.

`+123.4`

`-123.4`

Leading zeros are ignored.
----
>> +00123.4
== 123.4
----

Single quote `'` is used as a place value seperator for long integers, and can appear anywhere after the first digit.

----
>> 60'000'123.4
== 60000123.4
----


== Comparisons

All comparators can be applied on floats: `=, ==, <>, >, <, >=, &lt;=, =?`. In addition, `min`, and `max` are also supported.


== Conversion

A float value can be converted at runtime to `integer!` or `string!` by using the `to` action. 

[NOTE]
The digits after the decimal point will be discarded when converting a float to an integer. No rounding will take place.

----
>> to integer! 123.4
== 123

>> to string! 123.4
== "123.4"
----

If `float!` and `integer!` are combined in an expression, the result will be `float!`.

----
>> 123.4 * 42
== 5182.8
----


== Testing values

Use `float?` to check if a value is of the `float!` datatype.

----
>> float? 123.4
== true
----

Use `type?` to return the datatype of a given value.

----
>> type? 123.4
== float!
----
