= Pair! datatype
:toc:
:numbered:


== Abstract

The `pair!` datatype is used to represent two-dimensional coordinates.


== Literal syntax

A pair is written as two integers separated by an `x`.


`1024×768`

`-42x42`


== Creation

`Pair!` values can be created using literal syntax, or at runtime using a `make` constructor, `to` conversion, or via the as-pair `native!`.

```red
>> make pair! [20 30]
== 20x30

>> make pair! 42
== 42x42
```


```red
>> to pair! [20 30]
== 20x30

>> to pair! 42
== 42x42

>> to pair! "42x42"
== 42x42
```

`as-pair` takes an `x` and `y` argument of type `integer!` or `float!`. Float values will be truncated.

```red
>> as-pair 20 30
== 20x30

>> as-pair 1.23 42
== 1x42
```

== Comparisons

All comparators can be applied on pairs: `=, ==, <>, >, <, >=, &lt;=, =?`. In addition, `min`, and `max` are also supported.


== Arithmetic

`+`, `add`, `-`, `subtract`, `*`, `multiply`, `/`, `divide`, `%`, and `remainder` can be used with `pair!` values.


== Refinements

Pairs support the refinements `/x` and `/y` for viewing and modifying coordinates.

```red
>> my-pair: 1024x768
== 1024x768

>> my-pair/x
== 1024

>> my-pair/y
== 768

>> my-pair/y: 42
== 42

>> my-pair
== 1024x42
```



== Testing values

Use `pair?` to check if a value is of the `pair!` datatype.

```red
>> pair? 42x42
== true

>> pair? 42
== false
```

Use `type?` to return the datatype of a given value.

```red
>> type? 42x42
== pair!
```

== Pre-defined words


=== Actions

`absolute`, `add`, `and~`, `at`, `copy`, `divide`, `multiply`, `negate`, `or~`, `pick`, `remainder`, `reverse`, `round`, `skip`, `subtract`, `xor~`

=== Functions

`caret-to-offset`, `draw`, `first`, `make-face`, `metrics?`, `mod`, `modulo`, `offset-to-caret`, `offset-to-char`, `pair?`, `second`, `size-text`, `to-pair`, `within?`

=== Natives

`as-pair`, `case`, `extend`, `zero?`


=== Operators

`%`, `*`, `+`, `-`, `/`, `//`, `and`, `or`, `xor`

