= Tag! datatype
:toc:
:numbered:

== Abstract

`Tag!` values represent markup language tags and elements.

`Tag!` is a member of the following typesets: `any-string!`, `series!`

== Creation

Tag! values can be created using literal syntax, or at runtime by using a `make` constructor or `to` conversion.

```red
>> make tag! "foo"
== <foo>
```

```red
>> to tag! 'bar
== <bar>
```

== Literal syntax

One or more characters enclosed by a open angle bracket `<` and closing angle bracket `>`.

The first character after the opening angle bracket cannot be `<`, `>`, or `=`. 

Literal whitespace is not allowed between the opening angle bracket and the first character, as the lexer will interpret it as an invalid comparison operator.

```red
>> < foo>
*** Script Error: < operator is missing an argument
*** Where: catch
*** Stack:  
```

== Comparisons

All comparators can be applied on `tag!`: `=, ==, <>, >, <, >=, &lt;=, =?`. In addition, `min`, and `max` are also supported.

== Testing values

Use `tag?` to check if a value is of the `tag!` datatype.

```red
>> tag? <foo>
== true
```

Use `type?` to return the datatype of a given value.

```red
>> type? <foo>
== tag!
```

== Predefined words

=== Functions

`tag?`, `to-tag`