= Temporary notes

IMPORTANT: I apologize myself to prospective Norwegian colleges, that I have used their ISO language code *nn* as a list item in the LANGS.adoc file, denoting not a language mutation but this temporary annotative section of the documentation. I shall remove it when needed.

== Layout of the documentation

When visiting the http://www.gitbook.com/book/tovim/new-docs/details page, 
we can see a toggle button (*Language:* English) in the left corner of the page, which was created by GitBook technology, together with the *Read* button, top right.

The toggle button opens the English, Czech or (temporary) Annotations version of the respective README.adoc file.

One would expect, that the green *Read* button opens directly the access to the wanted documentation. +
Instead, the green Read button opens another page with another English, Czech and Annotations options.

NOTE: I do not know how to get rid of this redundant page.

After making a repeated selection, one gets to the desired page with a TOC for navigation at last.

The README.adoc file alone has two forms of appearance. The first one as a cover page with the `Language:` and `Read` buttons. The second presentation is the same, except of the `Language:` and `Read` buttons. This file appears as the first item of the TOC list. +
I would like to leave out this second appearance of the README file because it is superfluous also.

== Numbering of items

This numbering is easily attainable using the `:toc:` and `:numbered:` header attributes. Regrettably, it renders with bullets and numbers concurrently, which looks a little bit awkward. 

NOTE: I do not have any idea how to get rid of it.

It is neccessary to say, that for example the `Read the Docs` generator produces the same rendering.

== GitBook mashinery

The GB mashine is not able to render admonitions as for example the AsciidocFX editor can. 
Seemingly, the Gitbook doesn´t support the Asciidoctor processor. +
AsciidocFX is a nice desktop editor for editing and setting up neccessary files and folders as well as for viewing respective files. Saved changes in this editor are reflected immediately in the corresponding local repository. +
To get them reflected in GitBook, it is neccessary to git-push them to the GitHub repository.

To see the repository previewed in the browser, it is also possible using localhost server through the installed gitbook application: 

    .../new-docs> gitbook serve 
	
which is handy when editing source files repeatedly in (for example) Notepad++ editor.

To be able to handle the Gitbook toolchain on Windows, one needs to install the npm package manager, Nodejs, gitbook-cli and AsciidocFX editor, not to mention Git and Notepad++, which is not too demanding. 


	
    
= Invitation

Any sincere help and advice will be welcomed. The source code of the `new-docs` documentation is available at the https://github.com/Tovim/new-docs page.

Pavel Dolana, alias Tovim 
<jakubi@email.cz>
  


